server {
    listen 80;
    server_name apisms.robin.mba apisms.cloud59.ca;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name apisms.robin.mba apisms.cloud59.ca;
    ssl_certificate     /etc/nginx/ssl/fullchain1/fullchain.cer;
    ssl_certificate_key /etc/nginx/ssl/fullchain1/private.key;

    location /webhook/textlink {
        proxy_pass  http://192.168.0.21:55555/webhook/textlink;
        include     /etc/nginx/snippets/proxy-params.conf;
    }

    location / {
        proxy_pass  http://192.168.0.21:55555;
        include     /etc/nginx/snippets/proxy-params.conf;
    }
}
