server {
    listen 80;
    server_name missa.robin.mba;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name missa.robin.mba;
    ssl_certificate     /etc/nginx/ssl/fullchain1/fullchain.cer;
    ssl_certificate_key /etc/nginx/ssl/fullchain1/private.key;

    location / {
        return 302 https://designrr.page/?id=491821&token=3546574287&type=FP&h=6598;
    }
}
