server {
    listen 80;
    server_name n8n.robin.mba n8n.cloud59.ca;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name n8n.robin.mba n8n.cloud59.ca;
    ssl_certificate     /etc/nginx/ssl/fullchain1/fullchain.cer;
    ssl_certificate_key /etc/nginx/ssl/fullchain1/private.key;

    location / {
        proxy_pass  http://192.168.0.172:5678;
        include     /etc/nginx/snippets/proxy-params.conf;
    }
}
