server {
    listen 80;
    server_name paperless.robin.mba pdf.robin.mba;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name paperless.robin.mba pdf.robin.mba;
    ssl_certificate     /etc/nginx/ssl/fullchain1/fullchain.cer;
    ssl_certificate_key /etc/nginx/ssl/fullchain1/private.key;

    location / {
        proxy_pass  http://192.168.0.231:8000;
        include     /etc/nginx/snippets/proxy-params.conf;
    }
}
