server {
    listen 80;
    server_name robins.courses;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name robins.courses;
    ssl_certificate     /etc/nginx/ssl/fullchain1/fullchain.cer;
    ssl_certificate_key /etc/nginx/ssl/fullchain1/private.key;
    # NOTE: robins.courses (apex) not in SAN - cert warning until *.robins.courses provisioned

    location / {
        proxy_pass  http://192.168.0.56:80;
        include     /etc/nginx/snippets/proxy-params.conf;
    }
}
