server {
    listen 80;
    server_name tuba.robin.mba;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name tuba.robin.mba;
    ssl_certificate     /etc/nginx/ssl/fullchain1/fullchain.cer;
    ssl_certificate_key /etc/nginx/ssl/fullchain1/private.key;

    location / {
        proxy_pass          https://192.168.0.191:443;
        proxy_ssl_verify    off;
        proxy_buffers       16 16k;
        proxy_buffer_size   32k;
        include             /etc/nginx/snippets/proxy-params.conf;
    }
}
